<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGqHs4xp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGqHs4xp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGqHs4xp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGqHs4xp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGqHs4xp\App_KernelDevDebugContainer([
    'container.build_hash' => 'GqHs4xp',
    'container.build_id' => 'c1793b13',
    'container.build_time' => 1629413147,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGqHs4xp');
